/* eslint-disable */
// THIS FILE IS GENERATED BY @ember-gettext/gettext-parser
// DO NOT MODIFY THIS FILE YOURSELF - ANY CHANGE WILL BE OVERWRITTEN

const map = {
  de: () => import('./de.json'),
  en: () => import('./en.json'),
  ko: () => import('./ko.json')
};  

export default map;
